image: theimpulson/gitlab-ci-android:android-33

cache:
  - ~/.android
  - ~/.gradle

branches:
  test:
    - master

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --no-daemon -PstoreFile=$STORE_FILE -PstorePassword=$STORE_PASSWORD -PkeyAlias=$KEY_ALIAS -PkeyPassword=$KEY_PASSWORD "-Dorg.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError"
